Simplify misleading error message when an entry isn't found in a core module
e.g.
```koto
io.foo

Error: 'foo' not found in module 'map'
   |
 1 | io.foo
   |    ^^^
```

...which is caused by the fallback to looking for map operations. This would be
solvable by adding type names to each module's meta map, but it doesn't seem
worth it given the extra context provided in the error message.